CREATE TABLE CUSTOMER_SPECIMEN(
  last_name varchar(255),
  first_name varchar(255),
  customer_id VARCHAR(20),
  Chinese_name varchar(255),
  id_number varchar(40),
  passport_number varchar(40),
  sex enum('M', 'F'),
  date_of_birth VARCHAR(20),
  email varchar(255),
  phone varchar(255),
  ethnicity varchar(255),
  height VARCHAR(4),
  weight VARCHAR(4),
  city varchar(20),
  country varchar(255),
  postal_address varchar(255),
  postal_code VARCHAR(10),
  order_id VARCHAR(20) PRIMARY KEY UNIQUE,
  lab_id VARCHAR(20),
  reception_date varchar(255),
  collection_time VARCHAR(8),
  collection_date VARCHAR(20),
  specimen_type varchar(255),
  specimen_origin varchar(255),
  is_specimen_rejected enum('True', 'False'),
  previous_id varchar(20),
  panel_code varchar(255),
  panel_name varchar(255),
  is_tailormade enum('True', 'False'),
  test_performed_by varchar(255),
  clinic_name varchar(255),
  doctor_name varchar(255),
  concerned_issues varchar(255),
  S_quality varchar(255),
  emotion_problem varchar(255),
  project_code varchar(255),
  project_name varchar(255),
  clinic_trial_code varchar(255),
  clinic_trial_time_point varchar(255),
  is_free_sample enum('True', 'False'),
  extraction_date VARCHAR(20),
  test_date varchar(255),
  report_ready_date varchar(255),
  remarks varchar(255),
  medical_history varchar(255),
  status enum('PENDING','CANCELLED','DONE'),
  user varchar(50)
)
