
CREATE TABLE PET_SPECIMEN(
  pet_sex varchar(255),
  pet_name varchar(255),
  date_of_birth date,
  animal_type varchar(255),
  breed varchar(255),
  neutere_status varchar(255) UNIQUE,
  owner_surname varchar(255),
  owner_given_name varchar(255),
  email varchar(255),
  phone varchar(255),
  address varchar(255),

  postal_code INTEGER,
  reception_date varchar(255),
  order_id INTEGER,
  lab_id INTEGER,
  collection_time TIME,
  collection_date DATE,
  specimen_type varchar(255),
  specimen_origin varchar(255),
  is_specimen_rejected BOOLEAN,
  previous_id INTEGER,
  panel_code varchar(255),
  panel_name varchar(255),
  is_tailormade BOOLEAN,
  test_performed_by varchar(255),
  clinic_name varchar(255),
  doctor_name varchar(255),
  concerned_issues varchar(255),
  S_quality varchar(255),
  emotion_problem varchar(255),
  project_code varchar(255),
  project_name varchar(255),
  clinic_trial_code varchar(255),
  clinic_trial_time_point varchar(255),
  is_free_sample BOOLEAN,
  extraction_date INTEGER,
  test_date varchar(255),
  report_ready_date varchar(255),
  remarks varchar(255),
);
